### ISSUE TITLE
数据格式不一致

### ISSUE THREAD

**Issue by linLovexi** [ruini-classes/sdcs-testsuit#5]
测试的json数据和返回的json数据格式不一样，用来验证的json数据key和value之间少了一个空格
![错误](https://github.com/ruini-classes/sdcs-testsuit/assets/84257120/6a80511f-548f-4423-9cb7-553058b94c1c)

**Comment by fander1549** [comment]
貌似是macos的问题

**Comment by xueruini** [comment]
的确是，标准库dump出来的json应该是有个空格。现在不少同学都能跑过，不知道发生了什么

**Comment by xueruini** [comment]
打算用`jq`优化下比较

**Comment by xueruini** [comment]
@linLovexi PTAL #6

**Comment by xueruini** [comment]
找了几个同学验证了一下，应该可以了

**Comment by linLovexi** [comment]
好的老师，辛苦



---原始邮件---
发件人: "Ruini ***@***.***&gt;
发送时间: 2023年11月8日(周三) 中午11:50
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ruini-classes/sdcs-testsuit] 数据格式不一致 (Issue #5)




 
找了几个同学验证了一下，应该可以了
