### ISSUE TITLE
question

### ISSUE THREAD

**Issue by QAQbeginner** [ruini-classes/sdcs-testsuit#7]
jq: error: syntax error, unexpected ':', expecting '}' (Unix shell quoting issues?) at <top-level>, line 1:
jq: error: May need parentheses around object key expression at <top-level>, line 1:
在执行脚本时遇到了这两个问题，想问下是怎么回事，因为我自己单个运行命令是可以的

**Comment by xueruini** [comment]
```sh
❯ jq --version
jq-1.7
```

**Comment by xueruini** [comment]
1.6看起来要换个写法

```sh
ruini@ruini-zenbook14:~$ jq --version
jq-1.6
ruini@ruini-zenbook14:~$ idx=123
ruini@ruini-zenbook14:~$ jq -n --arg key "key-$idx" --arg value "value $idx" '{($key): ($value)}'
{
  "key-123": "value 123"
}
ruini@ruini-zenbook14:~$ jq -n --arg key "key-$idx" --arg value "value $idx" '{$key: $value}'
jq: error: syntax error, unexpected ':', expecting '}' (Unix shell quoting issues?) at <top-level>, line 1:
{$key: $value}
jq: error: May need parentheses around object key expression at <top-level>, line 1:
{$key: $value}
jq: 2 compile errors
```

![image](https://github.com/ruini-classes/sdcs-testsuit/assets/1863/d82bb2f0-af30-4b55-a336-09085bf5e943)

**Comment by xueruini** [comment]
![image](https://github.com/ruini-classes/sdcs-testsuit/assets/1863/a3bfd22b-3e99-422b-971a-a987f24a07f7)
